name: Auto test todo-app
on: push
env:
  PG_DATABASE: wd-todo-test
  PG_USER: postgres
  PG_PASSWORD: rank
jobs:
  # Label of the container job
  run-tests:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:11.7
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: rank
          POSTGRES_DB: wd-todo-test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test
      - name: Run the app
        id: run-app
        run: |
          docker-compose run app npx sequelize-cli db:drop
          docker-compose run app npx sequelize-cli db:create
          docker-compose run app npx sequelize-cli db:migrate
          docker-compose run app npm run start:dev &
          sleep 5
          sleep 5

      - name: Run integration tests
        run: |
          docker-compose run app npm install cypress cypress-json-results
          docker-compose run app npx cypress run --env STUDENT_SUBMISSION_URL="http://localhost:3000/"
          
      - name: Notify on success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"✨ Congratulations! The CI & CD pipeline ran successfully. All tests passed without any issues. :tada:"}' ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify on failure
        if: failure()
        run: |  
          curl -X POST -H 'Content-type: application/json' --data '{"text":"⚠️ Oops! The CI & CD pipeline encountered errors and failed. Immediate attention is required. :warning:"}' ${{ secrets.SLACK_WEBHOOK_URL }}
