name: Automat Docker CI & CD  
  
on: [ push ]  
  
jobs:  
  run-tests:  
    runs-on: ubuntu-latest  
  
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v3

      - name: Build Docker image  
        run: docker-compose build  
  
      - name: Run Docker Compose  
        run: docker-compose up -d & sleep 5  
  
      # - name: Run unit tests  
      #   run: docker-compose run app npm test  
  
      - name: Run app  
        run: |  
          docker-compose run app npx sequelize-cli db:drop  
          docker-compose run app npx sequelize-cli db:create  
          docker-compose run app npx sequelize-cli db:migrate  
          docker-compose run app npm run start:dev &
          sleep 5  
      - name: Run integration tests
        run: |
          docker-compose run app npx cypress run --env STUDENT_SUBMISSION_URL="http://localhost:3000/" 
  
      - name: Notify on success  
        if: success()  
        run: |  
          curl -X POST -H 'Content-type: application/json' --data '{"text":"✨ Great News! The CI & CD workflow completed successfully! All tests passed smoothly. :tada:"}' ${{ secrets.SLACK_WEBHOOK_URL }}  
  
      - name: Notify on failure  
        if: failure()  
        run: |  
          curl -X POST -H 'Content-type: application/json' --data '{"text":"⚠️ Uh-oh! The CI & CD workflow encountered issues and failed. Immediate attention is needed. :warning:"}' ${{ secrets.SLACK_WEBHOOK_URL }}  
  
      - name: Stop and remove Docker containers  
        run: docker-compose down